# Form implementation generated from reading ui file 'Add.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from pathlib import Path

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddLeaseDialog(object):
    def setupUi(self, AddLeaseDialog):
        AddLeaseDialog.setObjectName("AddLeaseDialog")
        AddLeaseDialog.resize(420, 500)
        self.vboxlayout = QtWidgets.QVBoxLayout(AddLeaseDialog)
        self.vboxlayout.setObjectName("vboxlayout")
        self.formlayout = QtWidgets.QFormLayout()
        self.formlayout.setObjectName("formlayout")
        self.label = QtWidgets.QLabel(parent=AddLeaseDialog)
        self.label.setObjectName("label")
        self.formlayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.branchInput = QtWidgets.QLineEdit(parent=AddLeaseDialog)
        self.branchInput.setObjectName("branchInput")
        self.formlayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.branchInput)
        self.label1 = QtWidgets.QLabel(parent=AddLeaseDialog)
        self.label1.setObjectName("label1")
        self.formlayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label1)
        self.headInput = QtWidgets.QLineEdit(parent=AddLeaseDialog)
        self.headInput.setObjectName("headInput")
        self.formlayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.headInput)
        self.label2 = QtWidgets.QLabel(parent=AddLeaseDialog)
        self.label2.setObjectName("label2")
        self.formlayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label2)
        self.contactInput = QtWidgets.QLineEdit(parent=AddLeaseDialog)
        self.contactInput.setPlaceholderText("")
        self.contactInput.setObjectName("contactInput")
        self.formlayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.contactInput)
        self.label3 = QtWidgets.QLabel(parent=AddLeaseDialog)
        self.label3.setObjectName("label3")
        self.formlayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label3)
        self.dateReceivedInput = QtWidgets.QDateEdit(parent=AddLeaseDialog)
        self.dateReceivedInput.setCalendarPopup(True)
        self.dateReceivedInput.setObjectName("dateReceivedInput")
        self.formlayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dateReceivedInput)
        self.label4 = QtWidgets.QLabel(parent=AddLeaseDialog)
        self.label4.setObjectName("label4")
        self.formlayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label4)
        self.termInput = QtWidgets.QLineEdit(parent=AddLeaseDialog)
        self.termInput.setObjectName("termInput")
        self.formlayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.termInput)
        self.label5 = QtWidgets.QLabel(parent=AddLeaseDialog)
        self.label5.setObjectName("label5")
        self.formlayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label5)
        self.fromDateInput = QtWidgets.QDateEdit(parent=AddLeaseDialog)
        self.fromDateInput.setCalendarPopup(True)
        self.fromDateInput.setObjectName("fromDateInput")
        self.formlayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.fromDateInput)
        self.label6 = QtWidgets.QLabel(parent=AddLeaseDialog)
        self.label6.setObjectName("label6")
        self.formlayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label6)
        self.toDateInput = QtWidgets.QDateEdit(parent=AddLeaseDialog)
        self.toDateInput.setCalendarPopup(True)
        self.toDateInput.setObjectName("toDateInput")
        self.formlayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.toDateInput)
        self.label7 = QtWidgets.QLabel(parent=AddLeaseDialog)
        self.label7.setObjectName("label7")
        self.formlayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label7)
        self.floorAreaInput = QtWidgets.QLineEdit(parent=AddLeaseDialog)
        self.floorAreaInput.setObjectName("floorAreaInput")
        self.formlayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.floorAreaInput)
        self.label8 = QtWidgets.QLabel(parent=AddLeaseDialog)
        self.label8.setObjectName("label8")
        self.formlayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label8)
        self.memoInput = QtWidgets.QLineEdit(parent=AddLeaseDialog)
        self.memoInput.setObjectName("memoInput")
        self.formlayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.FieldRole, self.memoInput)
        self.label9 = QtWidgets.QLabel(parent=AddLeaseDialog)
        self.label9.setObjectName("label9")
        self.formlayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label9)
        self.remarksInput = QtWidgets.QTextEdit(parent=AddLeaseDialog)
        self.remarksInput.setObjectName("remarksInput")
        self.formlayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.FieldRole, self.remarksInput)
        self.vboxlayout.addLayout(self.formlayout)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.saveButton = QtWidgets.QPushButton(parent=AddLeaseDialog)
        self.saveButton.setObjectName("saveButton")
        self.hboxlayout.addWidget(self.saveButton)
        self.cancelButton = QtWidgets.QPushButton(parent=AddLeaseDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.hboxlayout.addWidget(self.cancelButton)
        self.vboxlayout.addLayout(self.hboxlayout)

        self.retranslateUi(AddLeaseDialog)
        QtCore.QMetaObject.connectSlotsByName(AddLeaseDialog)

    def retranslateUi(self, AddLeaseDialog):
        _translate = QtCore.QCoreApplication.translate
        AddLeaseDialog.setWindowTitle(_translate("AddLeaseDialog", "Add Lease"))
        self.label.setText(_translate("AddLeaseDialog", "Branch:"))
        self.label1.setText(_translate("AddLeaseDialog", "Head:"))
        self.label2.setText(_translate("AddLeaseDialog", "Contact Number:"))
        self.label3.setText(_translate("AddLeaseDialog", "Date Received:"))
        self.label4.setText(_translate("AddLeaseDialog", "Term:"))
        self.label5.setText(_translate("AddLeaseDialog", "From:"))
        self.label6.setText(_translate("AddLeaseDialog", "To:"))
        self.label7.setText(_translate("AddLeaseDialog", "Floor Area:"))
        self.label8.setText(_translate("AddLeaseDialog", "Memo Number:"))
        self.label9.setText(_translate("AddLeaseDialog", "Remarks:"))
        self.saveButton.setText(_translate("AddLeaseDialog", "Save"))
        self.cancelButton.setText(_translate("AddLeaseDialog", "Cancel"))


class AddBranchDialog(QtWidgets.QDialog):
    """Adapter dialog used by Contract Expiry to collect a new branch row."""

    def __init__(self, headers=None, values=None, parent=None, title="Add Branch", theme="light"):
        super().__init__(parent)
        self.ui = Ui_AddLeaseDialog()
        self.ui.setupUi(self)
        self.setWindowTitle(title)

        self._values = list(values or [])
        if len(self._values) < 13:
            self._values.extend([""] * (13 - len(self._values)))

        self._apply_initial_values()
        self._configure_widget_names()
        self.apply_theme(theme)

        self.ui.saveButton.setText("Add Branch")
        self.ui.saveButton.clicked.connect(self.accept)
        self.ui.cancelButton.clicked.connect(self.reject)

    def _configure_widget_names(self):
        for label in (
            self.ui.label,
            self.ui.label1,
            self.ui.label2,
            self.ui.label3,
            self.ui.label4,
            self.ui.label5,
            self.ui.label6,
            self.ui.label7,
            self.ui.label8,
            self.ui.label9,
        ):
            label.setObjectName("modalLabel")

        for field in (
            self.ui.branchInput,
            self.ui.headInput,
            self.ui.contactInput,
            self.ui.termInput,
            self.ui.floorAreaInput,
            self.ui.memoInput,
        ):
            field.setObjectName("modalField")

        self.ui.remarksInput.setObjectName("modalField")

    def apply_theme(self, theme):
        assets_dir = Path(__file__).resolve().parent / "ui files"
        dark_arrow = (assets_dir / "date_arrow_dark.svg").as_posix()
        light_arrow = (assets_dir / "date_arrow_light.svg").as_posix()

        if theme == "dark":
            dark_style = """
                QDialog {
                    background-color: #0f1b2d;
                    color: #e2e8f0;
                    font-family: Segoe UI, Arial, sans-serif;
                    font-size: 13px;
                }
                QLabel#modalLabel {
                    color: #c2ddff;
                    font-weight: 700;
                }
                QLineEdit#modalField,
                QTextEdit#modalField,
                QDateEdit {
                    background-color: #0b1626;
                    color: #f8fafc;
                    border: 1px solid #29405e;
                    border-radius: 10px;
                    padding: 8px 10px;
                }
                QDateEdit::drop-down {
                    border-left: 1px solid #29405e;
                    width: 18px;
                    subcontrol-origin: padding;
                    subcontrol-position: top right;
                    background-color: #13243b;
                }
                QDateEdit::down-arrow {
                    image: url("__ARROW__");
                    width: 10px;
                    height: 6px;
                }
                QPushButton {
                    background-color: #1e63d7;
                    color: white;
                    border: none;
                    border-radius: 10px;
                    padding: 9px 14px;
                    font-weight: 700;
                }
                QPushButton:hover {
                    background-color: #3277ea;
                }
                """
            self.setStyleSheet(dark_style.replace("__ARROW__", dark_arrow))
            return

        light_style = """
            QDialog {
                background-color: #eef4fb;
                color: #17304d;
                font-family: Segoe UI, Arial, sans-serif;
                font-size: 13px;
            }
            QLabel#modalLabel {
                color: #27486f;
                font-weight: 700;
            }
            QLineEdit#modalField,
            QTextEdit#modalField,
            QDateEdit {
                background-color: #ffffff;
                color: #17304d;
                border: 1px solid #c9d8e6;
                border-radius: 10px;
                padding: 8px 10px;
            }
            QDateEdit::drop-down {
                border-left: 1px solid #c9d8e6;
                width: 18px;
                subcontrol-origin: padding;
                subcontrol-position: top right;
                background-color: #f5f9fd;
            }
            QDateEdit::down-arrow {
                image: url("__ARROW__");
                width: 10px;
                height: 6px;
            }
            QPushButton {
                background-color: #1f6feb;
                color: white;
                border: none;
                border-radius: 10px;
                padding: 9px 14px;
                font-weight: 700;
            }
            QPushButton:hover {
                background-color: #3180fb;
            }
            """
        self.setStyleSheet(light_style.replace("__ARROW__", light_arrow))

    def _parse_date(self, value):
        text = str(value or "").strip()
        if not text:
            return None
        for fmt in ("dd-MMM-yy", "d-MMM-yy", "yyyy-MM-dd", "dd/MM/yyyy", "MM/dd/yyyy"):
            parsed = QtCore.QDate.fromString(text, fmt)
            if parsed.isValid():
                return parsed
        return None

    def _set_date_edit(self, date_edit, value):
        parsed = self._parse_date(value)
        if parsed is None:
            parsed = QtCore.QDate.currentDate()
        date_edit.setDate(parsed)

    def _apply_initial_values(self):
        self.ui.branchInput.setText(self._values[0])
        self._set_date_edit(self.ui.dateReceivedInput, self._values[1])
        self.ui.termInput.setText(self._values[3])
        self.ui.headInput.setText(self._values[4])
        self.ui.contactInput.setText(self._values[5])
        self._set_date_edit(self.ui.fromDateInput, self._values[7])
        self._set_date_edit(self.ui.toDateInput, self._values[8])
        self.ui.floorAreaInput.setText(self._values[9])
        self.ui.memoInput.setText(self._values[10])
        self.ui.remarksInput.setPlainText(self._values[12])

        for field in (self.ui.dateReceivedInput, self.ui.fromDateInput, self.ui.toDateInput):
            field.setDisplayFormat("dd-MMM-yy")
            field.setCalendarPopup(True)

    def values(self):
        # Matches Contract Expiry row layout (13 columns; reminder at index 6 is computed).
        return [
            self.ui.branchInput.text().strip(),
            self.ui.dateReceivedInput.date().toString("dd-MMM-yy"),
            "",  # DATE SENT TO HO is not present in this generated UI.
            self.ui.termInput.text().strip(),
            self.ui.headInput.text().strip(),
            self.ui.contactInput.text().strip(),
            "",  # REMINDER is computed by store.reminder_date_for
            self.ui.fromDateInput.date().toString("dd-MMM-yy"),
            self.ui.toDateInput.date().toString("dd-MMM-yy"),
            self.ui.floorAreaInput.text().strip(),
            self.ui.memoInput.text().strip(),
            "",  # DATE COMPLETED/SENT is not present in this generated UI.
            self.ui.remarksInput.toPlainText().strip(),
        ]


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddLeaseDialog = AddBranchDialog(title="Add Branch", theme="light")
    AddLeaseDialog.show()
    sys.exit(app.exec())
